on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        otp: ["24.0"]
        elixir: ["1.12.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix deps.get
      - run: mix credo --strict
        continue-on-error: true
      - run: mix format --check-formatted
        continue-on-error: true
      - run: mix dialyzer
