on: push

jobs:
  test:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        otp-version:
          - "24.0.6"
        elixir-version: 
          - "1.12.3"
        mongo-version:
          - "4.4"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      # - run: MONGO_VERSION=${{ matrix.mongo-version}} docker-compose up -d
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongo-version }}
          mongodb-replica-set: rs0
          # mongodb-port: 42069
      - name: Install mongosh
        run: |
          # See https://docs.mongodb.com/mongodb-shell/install/
          wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
      - run: mix deps.get
      - run: mix credo --strict
        continue-on-error: true
      - run: mix format --check-formatted
        continue-on-error: true
      - run: mix dialyzer
      - run: mix test --cover
